
name: tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Bash on ${{ matrix.os }}
    steps:
          - uses: actions/checkout@v3
          - name: Run tests
            working-directory: tests
            run: sh batch_execute.sh
